[package]
name = "graph-cycles"
version = "0.1.0"
authors = ["Jakub Kwiatkowski <jakubkw99@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
log = "0.4.8"
fern = "0.6.0"
clap = "2.33.0"
chrono = "0.4.11"
