[package]
name = "graphs"
version = "0.1.0"
authors = ["Jakub Kwiatkowski <jakubkw99@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "1.9"
linked_hash_set = "0.1.3"
clap = "2.33.0"