name: Rust

on:
  push:
    branches: 
      - sorting
      - graphs

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1.1.2
      with:
        path: ./cache
        key:  ${{ runner.os }}-cached
    - name: Build
      run: 
        - cd ./graphs
        - cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Make docs
      run: cargo doc --verbose
